services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    restart: always
    ports:
      - "5440:5432"
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=codemash2025
      - POSTGRES_DB=meal_planner

  pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "8888:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "user@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    depends_on: 
      - db   